### ISSUE TITLE
How to add datetime in my schema?

### ISSUE THREAD

**Issue by oh3netid** [orionjs/orion#157]
Hello, I am using materialize with orion and having difficulty getting a schema with "datetime" to work. The default "Type: Date" is just a date and I need to specify time as well. Also, the default Date view looks wrong until you enter a valid date.

![0027-05-18 18 57 14](https://cloud.githubusercontent.com/assets/10240281/7678528/c9619c38-fd8f-11e4-8579-f7ba1d4e0dc1.jpg)
![0027-05-18 18 57 29](https://cloud.githubusercontent.com/assets/10240281/7678531/ce0f2cf0-fd8f-11e4-92a7-ed5a2116ad5e.jpg)

**Comment by rwatts3** [comment]
Use autoform and set the type of the afFieldIput to 'datetime' set autoform type to string.  You will get a field that allows date and time.  Also you can set he default value to Return new Date() for the current date and time.

**Comment by nicolaslopezj** [comment]
For a "material" way to do it use this:
```js
myDate: {
  type: Date
  autoform: {
    type:"pickadate"
  }
}
```

**Comment by oh3netid** [comment]
Thank you very much for the help! I eventually switched to bootstrap for datetimepicker. When I did so, my add button looked like this. How do I fix / customize it?

![0027-05-19 6 57 37](https://cloud.githubusercontent.com/assets/10240281/7691327/8a319b70-fdf4-11e4-9d66-2d354befb0c2.jpg)

**Comment by rwatts3** [comment]
Ok , if you are using bootstrap then you need to make sure bootstrap is installed. Keep in mind that if you are using materialize, than adding materialize and bootstrap will cause issues with classes. 
by looking at this screenshot it looks like you are using the materialize admin theme , so you will want to go with @nicolaslopezj suggestion above. Otherwise change your theme to `orionjs:bootstrap` and add `datetime` as the `afFieldInput` and set `autoform` to type of `String`

**Comment by oh3netid** [comment]
I'm pretty sure I'm using bootstrap now. Here are my meteor packages
meteor-platform
orionjs:core
coffeescript
dburles:collection-helpers
momentjs:moment
twbs:bootstrap
orionjs:bootstrap
aldeed:autoform-bs-datetimepicker
tsega:bootstrap3-datetimepicker@=3.1.3_3

Here's a full screen
![0027-05-19 7 05 55](https://cloud.githubusercontent.com/assets/10240281/7691468/947fb926-fdf5-11e4-9ded-4133edfa8cf5.jpg)

**Comment by rwatts3** [comment]
Hmm , you are correct. have you recently switched to the bootstrap theme ? 

If so try clearing your cache or opening in an incognito window and see if old styling got cached. Also try to stop the server and start it again , since you modified the type of that field it could have something to do with the update.

**Comment by nicolaslopezj** [comment]
do you have font awesome installed?

**Comment by rwatts3** [comment]
Good point Nicolas

On Monday, May 18, 2015, Nicolás López <notifications@github.com> wrote:

> do you have font awesome installed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orionjs/orion/issues/157#issuecomment-103228529>.
>


-- 
Ryan Watts
E.ryandwatts@gmail.com
C.520-442-8962
F.520-437-0914
IN. https://www.linkedin.com/in/ryandwatts

**Comment by oh3netid** [comment]
Thank you, that did it. May want to add that to the getting started docs. Also, is there a way to customize the button? Thanks again!

**Comment by rwatts3** [comment]
Yes there is you can grab the class of the button and add your own
styling.  If you want to specify don't awesome you'll need to modify your
own variant of the theme.



-- 
Ryan Watts
E.ryandwatts@gmail.com
C.520-442-8962
F.520-437-0914
IN. https://www.linkedin.com/in/ryandwatts

**Comment by oh3netid** [comment]
Thanks for your help!

**Comment by Teodi** [comment]
@oh3netid how did you manage to hear that datetimepicker on you orionjs panel from your front end?
