### ISSUE TITLE
Examples of admin API

### ISSUE THREAD

**Issue by ryanbuiltthat** [orionjs/orion#67]
There a few things I'd like to modify in the admin. For example, changing the text in the left column from Orion Admin to whatever....and changing that link so that it links back to the admin and not the home route. Is this possible already using the api? Are there more examples of ways we can override some things? Also, a couple times I've noticed that the `!important` declaration is made in the admin CSS. Overriding the styles is pretty easy but when you add that it becomes a little tricky to keep track of any CSS overrides especially any that traverse downward. Just a suggestion to try to refrain from using that.

**Comment by timfam** [comment]
@ryanbuiltthat Orion is very flexible, use dictionary link to modify the site name etc. You are right about the link. I am tracking it right now so @nicolaslopezj  can quickly update it to /admin. Also read the docs here http://orion.meteor.com/docs

**Comment by timfam** [comment]
@nicolaslopezj This needs to be fixed in bootsrap at line 69 ```<a href="/" class="navbar-brand">{{ dict 'siteName' 'Orion Admin'}}</a>``` change to  /admin

**Comment by nicolaslopezj** [comment]
It doesn't need to be fixed, we should add the option to define the link and also the default value of the definition if it is not defined

**Comment by timfam** [comment]
I disagree, common expectation is for admin theme logo or sitename to point to admin/home or dashboard not to live site. We should change to most common behavior and when we have free time in future extend it.

**Comment by rwatts3** [comment]
Actually this update was implemented in a pull request I submitted. I left the actual text of the link to default 'Orion Admin' since it seems most prominent to the system. And when the user defines the 'siteName' definition the site will inherit the name. Now I have built a separate application that adds a work around for long site names. 

Simply define another definition called siteLongName , and reference the long name where ever you want in the application, but the link to the site will always use the name of 'siteName'. The reason I did this is because there was no option to return to the home , or root , or starting point of the application once you are in side admin. For example before the PR you would have to go to the url bar and remove /admin  every time to get to the main page or hit back several times to get back to the landing page of the app. This is very inconvenient when you are building a mobile based application using orionjs. 

If you want to define the url of the link here is what i suggest. 

```js
<a href="{{ dict 'siteLink" '/' }} class="navbar-brand">{{ dict 'siteName' 'Orion Admin'}}</a>
```

If the user defines a definition of `{{siteLink}}` then it will go to what ever location they choose. 
@timfam I am not sure why we would want the link inside the admin panel to link to the admin panel the user is already currently working in. It would seem that if you are in the admin panel a quick home link should take you to the root location of the application you are working in. 

@ryanbuiltthat I wanted to address the `!important` issue , I do believe that there is a better way to do this and I believe I may have done it quickly when I was working on the pull request. I will make the update test and submit a PR to @nicolaslopezj . For now you should be safe in terms of styling since it was only on one attribute.

**Comment by ryanbuiltthat** [comment]
Thanks everyone. Just starting out I didn't eve put 2 and 2 together when thinking about dictionary definitions. I've been at this for a handful of hours already and most of the functionality I need is done and the site is functional. I chose orion because it really did seem like I could build what I needed quickly and I'm realizing that.

**Comment by timfam** [comment]
@rwatts3 I wrote a long reply and scratched it. Short answer it depends on use case. For now lets go with your solution. I appreciate you solving the problem of getting to home, I guess I need to add a back to admin page link to my app

**Comment by timfam** [comment]
@ryanbuiltthat I don't think Nick added a footer yet to the template, but this can be done easily and push into the next release you would simply add the dictionary in the template that you want displayed in the footer. i.e  ``` <template name="example">
    {{ dict 'myfootertext' 'default text just incase you forget to add content' }}
</template> ```
I should do a PR when I have some time to get to it for now skip it :)

**Comment by rwatts3** [comment]
@ryanbuiltthat 
I too when I started using Orion was so locked into structure, I didn't realize that it allowed me to change merely anything I wanted. So the `siteName` definition is simply a definition that I added into my app, I then realized that after building 3 apps I was constantly using `siteName` to reference things in my app. I did not have to modify any template files to get the `siteName` definition, I simply defined it then rendered it in my app with `{{dict 'siteName'}} `. 

So for your case like @timfam said you can define a definition called footer and simply use that in your template where ever you want the footer to be used. 

@timfam . If you go to this project I'm working on you can see where I have changed the orion logo at the top , to a bookmark logo of my own. That logo has a dictionary attribute that takes the user to /admin , from the front end of the site. If the user is not currently logged in it will take them to my website. 
coursenotes.wattsapplications.com

**Comment by rwatts3** [comment]
@ryanbuiltthat  Keep in mind that although Orion starts you with a lot of options out of the box, it also leaves a lot of room for extensibility. For instance not every user would want to use a footer, so simply defining a dictionary item for footer would work. 

I have done this in a mobile app by defining a dictionary group of `app` then anything related to the overall app such as footer, header content that I want on every page, and anything else can just be assigned to this dictionary group then you would add your definitions. 

Another thing that I am noticing is that a lot of different developers use similar tools on a specific type of project, but may not use those tools in other types of projects. To keep Orion extensible it would be good to add a small package or an extension that would add basic project type dictionary items so anyone can add it and go from there. 

For example take a look at this mobile app project i'm building 
clubencounters15.dev.wattsapplications.meteor.com

I wanted all of my boilerplate mobile app projects to have a dictionary for appName , appVersion , appContributors , and so on. 

So what I did was I created a package called orion-app-starter. And in that package I simply defined those dictionary items. Now, anytime I add this package to a project I will always start with those items. 

You could do the same with something like orion-website-starter. Then define a footer, header, sidecolumn or what ever you choose. And everytime you start a new project you will always have those items as a starter.

**Comment by rwatts3** [comment]
@ryanbuiltthat If you post a link or gist to the project you are working on or add it to nitrous.io I would be more than happy to jump in and give some pointers and show better ways to use Orion.

**Comment by ryanbuiltthat** [comment]
@rwatts3 So I think I see where I'm not getting it. I'm using Orion straight out of the box. Meaning I go to `/admin` and start adding my packages....and so on. 

If I'm understanding you correctly (and I may very well not be) I'm to build my own backend templates? Both you and @timfam mention the regular meteor template syntax but when you're just out of the box, where do those template calls go? I'm sorry if this is too much hand-holding, I get the concept of definitions, was able to make the site name change, and can use them effectively on the front end templates but that's because I'm creating those templates. It seems like that's where I'm disconnected? 

I'll get an example up shortly here but it seems like I'm trying to modify the default /admin ui when in fact I should be templating my own. My project is pretty basic which is why I wanted to use it as an opportunity to learn Orion. One page, some ScrollMagic and a tiny email function. The one page being served by the entities I'm setting in Orion. The admin will also need to be accessed by the client which is why I have extension additions. Again guys, I appreciate your time.

**Comment by timfam** [comment]
@ryanbuiltthat usually I do my developement by packages so I can reuse them just like @rwatts3 explained. My advise is download the example blog and play around with it. The structure is very instructive. Then ask your questions after, we are here to help :)

**Comment by rwatts3** [comment]
@ryanbuiltthat 
Okay I see exactly where you're coming from what you want to do is for or clone the example blog repository. 
Take a look at how the folder structure and the templates are set up. Anything that I am defining or doing inside of the Orion admin for instance defining definitions or defining entities you can put in a folder called Orion I usually put any folder or any templates or code that I am working with on my project inside of a folder structure card app. Inside of app you can define client server and live for files that are  nneed client/server seperation and so on. I used the example-blog to bootstrap my project and changed the organitzation where I saw neccesary. So at the root I have app , and orion . inside of app I have client , server, and anything I need directly relating to my app but not neccesarily using orion logic. Inside of orion I have a folder called entities, a folder called definition and a folder called pages. Inside of your app let's sayyou created a page . I would use the pages definition there, but I would actually define the orion page inside of orion/pages. 


Yeah this seems very similar to the first project I did , so when you get your repository up let me know because I'm sure myself and @timfam can point you in the right direction. Do not worry about hand holding here, the goal is to get many people exposure to how to use and build on Orion. So if that means lots of hand holding than so be it. To me hand holding gives me the opportunity to see how others interpret orion, and see how I can interpret it better for myself. When I first started with Orion I had a lot of hand holding myself.

**Comment by rwatts3** [comment]
When you look at the code documentation that @nicolaslopezj has provided inside of example-blog you will be amazed. This is a pure example of great and unprecedented documentation. He has done an extremely good job at explaining in the code why he assigned or did a code a specific way and the results to how that implementation will work. I can truly say everything if not most of what I have learned in terms of app structure has come from looking at his notes and comments within the actual code of example-blog.

**Comment by timfam** [comment]
@ryanbuiltthat we got your back just look at the example blog take a day if you need it, then come back with your questions :) and thanks @rwatts3 I appreciate you helping out the new guys. Investment in Orion will pay off big time

**Comment by rwatts3** [comment]
@timfam 
Thank you , 

I believe that every orion user has the ability to become great contributors to the system. Therefore helping new users get up to speed on the best practices , and how to Orion, as many of you have done for me will help grow the community at a more rapid pace. I have just created an issue in Orion Core letting @nicolaslopezj  know that I will be working on a tutorials application for Orion. It will be much like the example blog , and the coursenotes.wattsapplications.com project I showed you. Except the tutorials app will be real time step by step examples on how to build and structure an app the Orion way.

**Comment by rwatts3** [comment]
I will start with the example-blog , and build this on my current site, then once the application for official tutorials is complete I will migrate to that. @timfam if you want to help build it please let me know.

**Comment by timfam** [comment]
@rwatts3 more than happy to help!

**Comment by ryanbuiltthat** [comment]
Classic example of just diving in without checking if the pool is filled...the example blog is really illustrating some key points. I never even saw that link!! Thanks again, I do have more questions but I'll have examples, and more precise information for them tomorrow and maybe have worked through them.

**Comment by rwatts3** [comment]
@ryanbuiltthat No worries. When I build an application, or when I build an orion attribute I try to follow @nicolaslopezj example-blog as close as possible. It is a really good way to not only document to the end user how to build on the system, but it also helps you work through problems and solutions.

**Comment by nicolaslopezj** [comment]
@rwatts3, @timfam you are awesome, you really motivate me.
If you want more examples I have this repository with some websites I made https://github.com/madeby-nicolaslopezj. Check the version of orion first, some project use old ones.

I added @rwatts3 to the tutorials team, maybe you @timfam want that too?

Using definitions can solve a lot of problems, but my vision is this:
All things that are for developers must be in the code. Meaning this, we should create some functions to change titles, add a footer or other things. If we set it to the dictionary it can confuse the administrator of the site, which in most cases is not a developer.

**Comment by rwatts3** [comment]
@nicolaslopezj 
Since the creation and addition of users-attributes, and relationships I have managed to keep things seperate from the site administrator by defining a definition called app or dev. Anything that the developer would like to give to the site administrator can be assigned in other dictionary areas. But let's say the developer wanted to set a base footer, that he may or may not want to give to the site administrator , by defining it in side of a definition restricted to dev , this would allow for quick and rapid build without having to code in all areas of the site, you could set a user permission to admin on the dev definition group. This way when an administrator logs in they do not see the definition for dev , but if they wanted to quickly change their footer the developer/admin could go in and quickly deploy the updates with that dictionary item.

**Comment by nicolaslopezj** [comment]
@rwatts3 If was thinking of this, but I forgot to say:

Keep the changes in the code but the developer can set them to a definition, let me show you my idea

```js
orion.admin.setSidebarTitle(orion.dictionary.get('siteName'));
orion.admin.setSidebarTitle(orion.dictionary.get('siteLink'));
```

This leave the possibility to have both. And also you if you have that "orion-app-starter" package you can add that piece of code too there, so the changes would be applied automatically

**Comment by timfam** [comment]
This level of abstraction makes sense to me. We should really give admin
some awesome powers but be able to limit it based on permission and
experience

**Comment by timfam** [comment]
Yes this is the best of both world.

**Comment by rwatts3** [comment]
Great code example. 
Ok two questions. I am going to create the suite of starters so any user can start with predefined items as we've discussed, if they don't want the excessive bloatness , then they can simply not install the starter package. 

The question I have is , do we still need to define the definition in the dictionary but not assign it to a dictionay group. So if I did siteName do I still need to have it defined in the dictionary ?

**Comment by nicolaslopezj** [comment]
The thing that I'm saying is that we set the title or link to take the value of a definition, you can set it to any definition you want and of course you also need to define it

**Comment by rwatts3** [comment]
Oh I see that makes perfect sense.

**Comment by timfam** [comment]
,

**Comment by ryanbuiltthat** [comment]
Wow the sample blog is an awesome resource!

Few questions remain; can template level subscriptions be used?

Also I think a helpful feature would be contextual extensions. Similar to a
CMS called MODX where you have a manager (back end) and web (front end)
context. I actually was more than halfway through porting my project over
when I hit a conflict between Orion and materialize. Being more specific
with my styling helped a little. But to be able to scope a package or block
of code to the front end and not have orion pick it up would be awesome. Or
is that what namespacing is for?

This next one relates to my OP. I need to build a dashboard. One that shows
info from different entities and a whole lot more. Is it possible to extend
orion through templates and routes to accomplish this or should I fork the
repo and go that route?

At the moment I'm beyond impressed with orion, I just need to expand upon
administration view a bit but holy crap did it turn a nightmare of editing
a parallax page into a cake walk!

**Comment by nicolaslopezj** [comment]
@ryanbuiltthat 

Yes, you can use template level subscriptions.

Thats a problem right now, the admin is loaded in all routes. A solution could be to fork orionjs/bootstrap and make it materialize.

Yes you can extend the admin, check here https://github.com/orionjs/core/tree/master/api#adding-tabs

**Comment by rwatts3** [comment]
@ryanbuiltthat 
Another thing to note is that when you create your side tabs and custom routes, don't forget to render the adminLayout when you create the route, so that your custom admin item looks and feels like it belongs in the admin area. 

I noticed this when I tried to add an analytics option to orion, but forgot to use the layout template of Orion Admin. Once I added the layout template to my route, the analytics option looked a lot cleaner.

See the FileSystem repository for an example on how to do such a thing.
